baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-map'

[module]
  # Build and serve using local mod-map clone declared in the named Hugo workspace:
  workspace = "mod-map.work"
  [[module.imports]]
    path = "github.com/oolonek/mod-map"
  [[module.imports.mounts]]
    source = "dist"
    target = "static"
  [[module.imports.mounts]]
    source = "layouts"
    target = "layouts"